CMS\SharedBundle\Entity\Block:
    type: entity
    table: block
    fields:
        id:
            id: true
            type: integer
            unsigned: true
            nullable: false
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 45
            fixed: false
            nullable: true
        description:
            type: string
            length: 1024
            fixed: false
            nullable: true                    
        created:
            type: datetime
            nullable: false
            gedmo:
              timestampable:
                on: create
        updated:
            type: datetime
            nullable: false
            gedmo:
              timestampable:
                on: update                        
    oneToMany:
        parent:
          targetEntity: BlockInstance
          mappedBy: block          
        child: 
          targetEntity: BlockInstance
          mappedBy: parent          
    manyToOne:      
        type:
            targetEntity: BlockType                        
            joinColumns:
                block_type_id:
                    referencedColumnName: id
            orphanRemoval: false
        currentRevision:
            targetEntity: BlockRevision            
            inversedBy: BlockRevision
            joinColumns:
                current_revision_id:
                    referencedColumnName: id
            orphanRemoval: false                   
    lifecycleCallbacks: {  }