CMS\SharedBundle\Entity\BlockType:
    type: entity
    table: block_type
    fields:
        id:
            id: true
            type: integer
            unsigned: true
            nullable: false
            generator:
                strategy: IDENTITY
        name:
          type: string
          length: 64
    oneToMany:
        block:
          targetEntity: Block
          mappedBy: type
          
    lifecycleCallbacks: {  }
