CMS\SharedBundle\Entity\BlockType:
    type: entity
    table: block_type
    fields:
        id:
            id: true
            type: integer
            unsigned: true
            nullable: false
            generator:
                strategy: IDENTITY
    lifecycleCallbacks: {  }
