CMS\SharedBundle\Entity\BlockRevision:
    type: entity
    table: block_revision
    fields:
        id:
            id: true
            type: integer
            unsigned: true
            nullable: false
            generator:
                strategy: IDENTITY
        revision: 
            type: integer
            unsigned: true
            nullable: false
        content:
            type: text
            nullable: true
        created:
            type: datetime
            nullable: false
            gedmo:
              timestampable:
                on: create
        updated:
            type: datetime
            nullable: false
            gedmo:
              timestampable:
                on: update            
    manyToOne:
        block:
            targetEntity: Block
            cascade: {  }
            joinColumns:
                block_id:
                    referencedColumnName: id
            orphanRemoval: false
        editor:
            targetEntity: User
            cascade: {  }
            joinColumns:
                editor_id:
                    referencedColumnName: id
            orphanRemoval: false
        template:
            targetEntity: Template
            inversedBy: template            
    oneToMany:
        setting:
            targetEntity: BlockSetting              
            mappedBy: setting
          
    lifecycleCallbacks: {  }
