CMS\SharedBundle\Entity\BlockSetting:
    type: entity
    table: block_setting
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: '255'
        created:
            type: datetime
            nullable: false
            gedmo:
              timestampable:
                on: create
        updated:
            type: datetime
            nullable: false
            gedmo:
              timestampable:
                on: update                        
    manyToOne:
      revision:
          targetEntity: BlockRevision                                        
          orphanRemoval: false    
          inversedBy: blockRevision
    oneToMany:
        value:
            targetEntity: BlockSettingValue
            mappedBy: blockSettingValue
    lifecycleCallbacks: {  }
