CMS\SharedBundle\Entity\BlockInstance:
    type: entity
    table: block_instance
    fields:
        id:
            id: true
            type: integer
            unsigned: true
            nullable: false
            generator:
                strategy: IDENTITY
        sortOrder:
            type: integer
            unsigned: true
            nullable: true
            column: sort_order        
            gedmo:
                - sortablePosition
    manyToOne:
        parent:
            targetEntity: Block            
            orphanRemoval: false
        template:
            targetEntity: Template
            orphanRemoval: false               
        block:
            targetEntity: Block            
            orphanRemoval: false
    lifecycleCallbacks: {  }
