CMS\SharedBundle\Entity\BlockSettingValue:
    type: entity
    table: block_setting_value
    gedmo: 
      loggable: true
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        value:
            type: string
            length: '255'
            gedmo:
                - versioned
    manyToOne:
      setting:
        targetEntity: BlockSetting
        inversedBy: value
        orphanRemoval: true
    lifecycleCallbacks: {  }
