CMS\SharedBundle\Entity\ContainerChild:
    type: entity
    table: container_child
    fields:
        id:
            id: true
            type: integer
            unsigned: true
            nullable: false
            generator:
                strategy: IDENTITY
        sortOrder:
            type: integer
            unsigned: true
            nullable: true
            column: sort_order        
            gedmo:
                - sortablePosition
    manyToOne:
        parent:
            targetEntity: Container
            inversedBy: child            
            orphanRemoval: false
        template:
            targetEntity: Template
            orphanRemoval: false               
        child:
            targetEntity: Container
            inversedBy: parent
            orphanRemoval: false
    lifecycleCallbacks: {  }
