CMS\SharedBundle\Entity\Group :
    type: entity
    table: usergroup
    fields:
        id:
            id: true
            type: integer
            unsigned: true
            nullable: false
            generator:
                strategy: AUTO