CMS\SharedBundle\Entity\Layout:
    type: entity
    table: layout
    fields:
        id:
            id: true
            type: integer
            unsigned: true
            nullable: false
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 128
            fixed: false
            nullable: false
        description:
            type: string
            length: 512
            fixed: false
            nullable: true
        
        created:
            type: datetime
            nullable: false
            gedmo:
              timestampable:
                on: create
        updated:
            type: datetime
            nullable: false
            gedmo:
              timestampable:
                on: update           
    manyToOne:
        rootBlock:
            targetEntity: Block
            inversedBy: layouts
            joinColumns:
                root_block_id:
                    referencedColumnName: id
            orphanRemoval: false                            
        author:
            targetEntity: User
            orphanRemoval: false               
        editor:
            targetEntity: User
            orphanRemoval: false               
    lifecycleCallbacks: {  }
    
