CMS\SharedBundle\Entity\Metadata:
    type: entity
    table: metadata
    fields:
        id:
            id: true
            type: integer
            unsigned: true
            nullable: false
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 45
            fixed: false
            nullable: true
    lifecycleCallbacks: {  }
