CMS\SharedBundle\Entity\Page:
    type: entity
    table: page
    fields:
        id:
            id: true
            type: integer
            unsigned: true
            nullable: false
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 512
            fixed: false
            nullable: true
        slug:
            type: string
            length: 512
            fixed: false
            nullable: true
        created:
            type: datetime
            nullable: false
            gedmo:
              timestampable:
                on: create
        updated:
            type: datetime
            nullable: false
            gedmo:
              timestampable:
                on: update                                     
    manyToMany:
        category:
            targetEntity: PageCategory
            cascade: {  }
            inversedBy: page
            joinTable:
                name: page_page_category
                joinColumns:
                    -
                        name: page_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: page_category_id
                        referencedColumnName: id
            orderBy: null
    manyToOne:
        author:
            targetEntity: User
            cascade: {  }
            joinColumns:
                author_id:
                    referencedColumnName: id
            orphanRemoval: false        
        currentRevision:
            targetEntity: PageRevision
            cascade: {  }
            joinColumns:
                current_page_revision_id:
                    referencedColumnName: id
            orphanRemoval: false
    oneToMany:
      revisions:
            targetEntity: PageRevision
            mappedBy: PageRevision
            orphanRemoval: false
    lifecycleCallbacks: {  }
