CMS\SharedBundle\Entity\PageGeneration:
    type: entity
    table: page_generation
    fields:
        id:
            id: true
            type: integer
            unsigned: true
            nullable: false
            generator:
                strategy: IDENTITY
        timeGenerated:
            type: datetime
            nullable: true
            column: time_generated
    manyToOne:
        pageRevision:
            targetEntity: PageRevision
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                page_revision_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
