CMS\SharedBundle\Entity\PageRevision:
    type: entity
    table: page_revision
    fields:
        id:
            id: true
            type: integer
            unsigned: true
            nullable: false
            generator:
                strategy: IDENTITY        
        revision:
            type: integer            
            unsigned: true
            nullable: false
        created:
            type: datetime
            nullable: false
            gedmo:
              timestampable:
                on: create
        updated:
            type: datetime
            nullable: false
            gedmo:
              timestampable:
                on: update            
        publishApproved:
            type: boolean
            nullable: false
            column: publish_approved
    manyToOne:
        page:
            targetEntity: Page
            inversedBy: revisions
            orphanRemoval: true
        editor:
            targetEntity: User
            inversedBy: null            
            orphanRemoval: false
        rootBlock:
            targetEntity: Block
            inversedBy: pages
            joinColumns:
                root_block_id:
                    referencedColumnName: id
            orphanRemoval: false
        approver:
            targetEntity: User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                approver_id:
                    referencedColumnName: id
            orphanRemoval: false        
    lifecycleCallbacks: {  }
