parameters:
#    cms_security.example.class: CMS\SecurityBundle\Example

services:
#    cms_security.example:
#        class: %cms_security.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
