
        
# rest routes

blocks:
  type: rest
  resource: CMS\PageBundle\Block\BlockCRUDController

instances:
  type: rest
  resource: CMS\PageBundle\Block\BlockCRUDController
  
layouts:
  type: rest
  resource: CMS\PageBundle\Layout\LayoutCRUDController
  
pages:
  type: rest
  resource: CMS\PageBundle\Page\PageCRUDController
  
templates:
  type: rest
  resource: CMS\PageBundle\Template\TemplateCRUDController


# standard routes


cms_page_view:
    pattern: /{pageSlug}/
    defaults: { _controller: CMSPageBundle:RenderPage:view, pageSlug: 'index', style: 'core' }
    requirements:
      pageSlug: ".+"
           
cms_page_default: 
    pattern: /
    defaults: { _controller: CMSPageBundle:RenderPage:view, pageSlug: 'index' }
