cms_page_default: 
    pattern: /
    defaults: { _controller: CMSPageBundle:RenderPage:view, pageSlug: 'index' }

cms_page_view:
    pattern: /{pageSlug}/
    defaults: { _controller: CMSPageBundle:RenderPage:view, pageSlug: 'index', style: 'core' }
    requirements:
      pageSlug: ".+"
   
cms_page_edit:
    pattern: /{pageSlug}/edit/
    defaults: { _controller: CMSPageBundle:RenderPage:edit, pageSlug: 'index' }
    requirements:
        _method:  GET
    
cms_page_edit_process:
    pattern: /{pageSlug}/edit/
    defaults: { _controller: CMSPageBundle:RenderPage:edit, pageSlug: 'index' }
    requirements:
        _method:  POST                   