#import rest routes
cms_page_rest:
  type: rest
  resource: "@CMSPageBundle/Resources/config/routing-rest.yml"    

# standard routes
cms_page_view:
    pattern: /{pageSlug}/
    defaults: { _controller: CMSPageBundle:RenderPage:view, pageSlug: 'index'}
    requirements:
      pageSlug: ".+"
           
cms_page_default: 
    pattern: /
    defaults: { _controller: CMSPageBundle:RenderPage:view, pageSlug: 'index' }
