
        
# rest routes

blocks:
  type: rest
  resource: CMS\PageBundle\Block\BlockCRUDController

instances:
  type: rest
  resource: CMS\PageBundle\Block\BlockCRUDController

layouts:
  type: rest
  resource: CMS\PageBundle\Layout\LayoutCRUDController
  
pages:
  type: rest
  resource: CMS\PageBundle\Page\PageCRUDController
  
templates:
  type: rest
  resource: CMS\PageBundle\Template\TemplateCRUDController
  