
        
# rest routes

blocks:
  type: rest
  resource: CMS\PageBundle\Block\BlockCRUDController
  
pages:
  type: rest
  resource: CMS\PageBundle\Page\PageCRUDController
  
templates:
  type: rest
  resource: CMS\PageBundle\Template\TemplateCRUDController


# standard routes


cms_page_view:
    pattern: /{pageSlug}/
    defaults: { _controller: CMSPageBundle:RenderPage:view, pageSlug: 'index', style: 'core' }
    requirements:
      pageSlug: ".+"
   
cms_page_edit:
    pattern: /{pageSlug}/edit/
    defaults: { _controller: CMSPageBundle:RenderPage:edit, pageSlug: 'index' }
    requirements:
        _method:  GET
    
cms_page_edit_process:
    pattern: /{pageSlug}/edit/
    defaults: { _controller: CMSPageBundle:RenderPage:edit, pageSlug: 'index' }
    requirements:
        _method:  POST                   
        
cms_page_default: 
    pattern: /
    defaults: { _controller: CMSPageBundle:RenderPage:view, pageSlug: 'index' }
