parameters:
    container_manager.class: CMS\PageBundle\Container\ContainerManager
    page_manager.class: CMS\PageBundle\Page\PageManager
    
services:
#    cms_page.example:
#        class: %cms_page.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    response:
        class:        Symfony\Component\HttpFoundation\Response
    request:
        class:        Symfony\Component\HttpFoundation\Request
    
    container_manager:
        class: "%container_manager.class%"
        arguments: [@doctrine.orm.entity_manager]
                
    page_manager:
        class: "%page_manager.class%"
        arguments: [@doctrine.orm.entity_manager, @container_manager]        