parameters:
    block_manager.class: CMS\PageBundle\Block\BlockManager
    page_manager.class: CMS\PageBundle\Page\PageManager
    
    
services:
#    cms_page.example:
#        class: %cms_page.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    response:
        class:        Symfony\Component\HttpFoundation\Response
    request:
        class:        Symfony\Component\HttpFoundation\Request

    
    block_manager:
        class: "%block_manager.class%"
        default_template: %cms_page.default_template%
        arguments: [@doctrine.orm.entity_manager, @templating]
                
    page_manager:
        class: "%page_manager.class%"
        default_template: %cms_page.default_template%
        arguments: [@doctrine.orm.entity_manager, @block_manager, @templating]        