parameters:
    container_manager.class: CMS\PageBundle\Container\ContainerManager
    page_manager.class: CMS\PageBundle\Page\PageManager
    
    
services:
#    cms_page.example:
#        class: %cms_page.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    response:
        class:        Symfony\Component\HttpFoundation\Response
    request:
        class:        Symfony\Component\HttpFoundation\Request

    
    container_manager:
        class: "%container_manager.class%"
        default_template: %cms_page.default_template%
        arguments: [@doctrine.orm.entity_manager, @templating]
                
    page_manager:
        class: "%page_manager.class%"
        default_template: %cms_page.default_template%
        arguments: [@doctrine.orm.entity_manager, @container_manager, @templating]        